export const OPEN_CODE_NUMBER_SCREEN = 'OPEN_CODE_NUMBER_SCREEN'
export const OPEN_PHONE_NUMBER_SCREEN = 'OPEN_PHONE_NUMBER_SCREEN'
export const OPEN_PROFILE_SCREEN = 'OPEN_PROFILE_SCREEN'
export const OPEN_PRINCIPAL_SCREEN = 'OPEN_PRINCIPAL_SCREEN'
